config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#splash'

  get 'splash', to: 'pages#splash'

  resources :categories do
    resources :transactions, only: %i[index new create], controller: 'transactions'
  end

  resources :users, only: [:index] do
    resources :categories
  end

  get '/categories/new', to: 'categories#new', as: 'new_category_form'

  authenticated :user do
    root 'categories#index', as: :authenticated_root
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :transaction_categories, foreign_key: :category_id
  has_many :transactions, through: :transaction_categories, source: :transaction_record

  attribute :icon_url, :string
  validates :name, presence: true

  def total_amount
    transactions.sum(:amount)
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :transaction_categories, foreign_key: :transaction_record_id
  has_many :categories, through: :transaction_categories

  validates :name, presence: true
  validates :amount, presence: true
end

app/models/transaction_category.rb
class TransactionCategory < ApplicationRecord
  belongs_to :category, foreign_key: :category_id
  belongs_to :transaction_record, foreign_key: :transaction_record_id, class_name: 'Transaction'
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories, dependent: :destroy
  has_many :transactions, foreign_key: :author_id, dependent: :destroy, inverse_of: :author

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @categories = @user.categories.includes(:transactions)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.user = current_user

    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon_url, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def splash
    if user_signed_in?
      redirect_to categories_path
    else
      render 'splash'
    end
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @category = Category.includes(:transactions).find(params[:category_id])
    @transactions = @category.transactions.order(created_at: :desc)
    @total_amount = @category.total_amount
  end

  def new
    @category = Category.find(params[:category_id])
    @transaction = Transaction.new
  end

  def create
    @category = Category.find(params[:category_id])
    @transaction = Transaction.new(transaction_params.merge(author_id: current_user.id))

    if @transaction.save
      @transaction.transaction_categories.create(category_id: @category.id)
      redirect_to category_transactions_path(@category), notice: 'Transaction created successfully.'
    else
      render :new
    end
  end

  private

  def transaction_params
    params.require(:transaction).permit(:name, :amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
# app/helpers/pages_helper.rb
module PagesHelper
  def custom_helper_method
    'Hello, World!'
  end
end

app/views/categories/index.html.erb
<head>
<style>
  body {
      min-height: 100vh;
      display: flex;
      flex-direction: column;
      justify-content: flex-start;
      background-color: #f1f1f1;
      margin: 0;
      border: 1px solid;
      border-radius: 1rem;
      align-items: stretch;
    }

    .header {
    display: flex;
    justify-content: center;
    background-color: #3778c2;
    color: #fff;
    height: 7rem;
    align-items: center;
    border-top-left-radius: 14px;
    border-top-right-radius: 14px;
    }

    h1 {
      text-align: center;
      font-family: 'Proxima Nova', 'sans-serif';
      font-weight: normal;
      color: #fff;
    }

    h2 {
      font-size: 24px;
      margin-bottom: 20px;
      color: #fff;
    }

  /* Text Styles */
  p {
    text-align: center;
    margin: 0;
  }

  /* List Styles */
  ul {
    list-style: none;
    padding: 0;
    margin: 0;
  }

  li {
    display: flex;
    align-items: center;
    justify-content: space-between;
    background-color: #fff;
    padding: 10px;
    margin-bottom: 1rem;
  }

  li p {
    font-family: 'Proxima Nova', sans-serif;
    font-weight: bold;
    color: #3778c2;
    margin: 0;
  }

 /* Button Styles */
  .button {
    display: inline-block;
    padding: 10px 20px;
    background-color: #3778c2;
    color: #fff;
    text-decoration: none;
    font-family: 'Proxima Nova', sans-serif;
    font-weight: bold;
    border-radius: 4px;
  }

 /* Footer Styles */
  footer {
background-color: #5fb523;
    color: #fff;
    text-align: center;
    position: fixed;
    bottom: 0;
    left: 0;
    width: 100%;
    border-bottom-left-radius: 1rem;
    border-bottom-right-radius: 1rem;
    height: 16vh;
    display: flex;
    align-items: center;
    justify-content: center;
  }
.logout-button {
  margin-left: -8rem;
      padding: 12px 24px;
    font-size: larger;
    background-color: #3778c2;
    color: #fff;
    text-decoration: none;
    border: white;
    border-radius: 4px;
    transition: background-color 0.3s;
}
.add-category-button {
background-color: #5fb523;
    color: #fff;
    font-size: x-large;
    border: 1px solid;
    padding: 1rem;
}
    /* Category Styles */
    .categories-container {
        display: flex;
        flex-direction: column;
        gap: 1rem;
      }
   a {
  text-decoration: none;
    color: #424242;
    font-style: normal;
}
      .category {
        display: flex;
        align-items: center;
        height: 5rem;
        justify-content: space-between;
        background-color: #fff;
        padding: 10px;
        margin-top: 1rem;
      }
   
   .notice {
    display: none;
   }
      .name {
        font-family: 'Proxima Nova', sans-serif;
        font-weight: bold;
        color: #3778c2;
        flex: 1;
        text-align: center;
        margin: 0;
      }
    
      .category p {
        text-align: center;
        margin: 0;
      }
    
      .category img {
        width: 20%;
        height: 100%;
        object-fit: contain;
      }
      </style>
      </head>
<div class='header'>
    <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "logout-button" %>
<h1>CATEGORY</h1>
</div>
<div class="categories-container">
  <% @categories.each do |category| %>
    <div class="category">
    <% if category.icon_url.present? %>
        <img src="<%= category.icon_url %>" alt="Category Icon" />
      <% else %>
        <p>No Icon</p>
      <% end %>
      <h2><%= link_to category.name, category_transactions_path(category) %></h2>
      <p>Total Amount: $<%= category.total_amount %></p>
      
    </div>
  <% end %>
</div>
<footer>
  <%= button_to "ADD A NEW CATEGORY", new_category_path, method: :get, class: "add-category-button" %>
    </footer>
    

app/views/categories/new.html.erb
<head>
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

  <style>
    body {
      min-height: 100vh;
      display: flex;
      flex-direction: column;
      justify-content: flex-start;
      background-color: #f1f1f1;
      margin: 0;
      border: 1px solid;
      border-radius: 1rem;
      align-items: stretch;
    }

    .header {
    display: flex;
    gap: 1rem;
    margin-left: 1re;
    background-color: #3778c2;
    color: #fff;
    height: 8rem;
    align-items: center;
    border-top-left-radius: 14px;
    border-top-right-radius: 14px;
    }

    h1 {
    text-align: center;
    font-family: 'Proxima Nova', 'sans-serif';
    font-weight: normal;
    font-size: x-large;
    color: #fff;
    }

    h2 {
      font-size: 24px;
      margin-bottom: 20px;
      color: #fff;
    }

    .actions {
      text-align: right;
      margin-top: 10px;
    }

    .back-link {
      color: #fff;
      text-decoration: none;
      margin-right: 10px;
      font-size: 20px;
    }

    .field {
      margin-bottom: 10px;
    }

    label {
      display: block;
      font-weight: bold;
      color: #fff;
    }

    input[type="text"],
    input[type="email"],
    input[type="password"],
    input[type="checkbox"] {
      width: 92%;
      padding: 10px;
      font-size: 16px;
      border-radius: 4px;
      border: 1px solid #5fb523;
      margin-left: 5px;
      margin-right: 5px;
      height: 2rem;
      margin-top: 5px;
    }

    input[type="submit"] {
    padding: 12px 24px;
    position: fixed;
    font-size: larger;
    background-color: #3778c2;
    color: #fff;
    text-decoration: none;
    border: white;
    border-radius: 4px;
    transition: background-color 0.3s;
        margin-top: -12.7rem;
    width: 100#;
    margin-left: 18rem;
    }

    input[type="submit"]:hover {
      background-color: #5fb523;
    }

     p {
      display: none;
      }

    .material-icons {
      font-family: 'Material Icons';
      margin-left: 1rem;
      font-style: normal;
      font-size: x-large;
    }
  </style>
</head>
<div class='header'>
<h2><%= link_to categories_path, class: 'back-link' do %><i class="material-icons">arrow_back</i><% end %></h2>
<h1>Add a new category</h1>
</div>
<%= form_with(model: @category, url: categories_path, local: true) do |form| %>
  <div>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div>
    <%= form.text_field :name, required: true , placeholder: "Enter the category name please"%>
  </div>


<div>
 <%= form.label :icon_url, 'Icon URL', style: 'display: none;' %>

  <%= form.text_field :icon_url, required: true, placeholder: "Enter the icon url" %>
</div>


  <%= form.submit 'Save' %>
<% end %>

app/views/indices/_form.html.erb
<%= form_with(model: index) do |form| %>
  <% if index.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(index.errors.count, "error") %> prohibited this index from being saved:</h2>

      <ul>
        <% index.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/indices/_index.html.erb
<div id="<%= dom_id index %>">
</div>

app/views/indices/edit.html.erb
<h1>Editing index</h1>

<%= render "form", index: @index %>

<br>

<div>
  <%= link_to "Show this index", @index %> |
  <%= link_to "Back to indices", indices_path %>
</div>

app/views/indices/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Indices</h1>

<div id="indices">
  <% @indices.each do |index| %>
    <%= render index %>
    <p>
      <%= link_to "Show this index", index %>
    </p>
  <% end %>
</div>

<%= link_to "New index", new_index_path %>

app/views/indices/new.html.erb
<h1>New index</h1>

<%= render "form", index: @index %>

<br>

<div>
  <%= link_to "Back to indices", indices_path %>
</div>

app/views/indices/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @index %>

<div>
  <%= link_to "Edit this index", edit_index_path(@index) %> |
  <%= link_to "Back to indices", indices_path %>

  <%= button_to "Destroy this index", @index, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/pages/splash.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Your App Name - Splash</title>
  <style>
 body {
    min-height: 94vh;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    align-items: center;
    background-color: #f2f2f2;
    margin: 0;
    padding: 20px;
    border: 1px solid;
    border-radius: 1rem;
}

.container {
text-align: center;
    display: flex;
    flex-direction: column-reverse;
    align-items: stretch;
    margin-bottom: 1rem;
    height: 12rem;
    padding: 2rem;
}

h1 {
   font-family: 'Proxima Nova';
  font-size: 50px;
  font-style: italic;
  margin-bottom: 20px;
  color: #434b54;
}

.btn {
    display: flex;
    padding: 12px 24px;
    font-size: 24px;
    background-color: #fff;
    color: #434b54;
    text-decoration: none;
    border-radius: 4px;
    transition: background-color 0.3s;
    margin-bottom: 10px;
    border: 1px solid;
    height: 2.5rem;
    width: 298px;
    align-items: center;
    justify-content: center;
}

.btn:hover {
  background-color: #3778c2;
  color: #fff;
}

  </style>
</head>
<body>
<h1>Snaps can</h1>
  <div class="container">
     <a href="<%= new_user_registration_path %>" class="btn">Sign Up</a>
    <a href="<%= new_user_session_path %>" class="btn">Log In</a>
  </div>
</body>
</html>

app/views/transactions/index.html.erb
<!-- app/views/transactions/index.html.erb -->
<head>
<style>
  body {
      min-height: 100vh;
      display: flex;
      flex-direction: column;
      justify-content: flex-start;
      background-color: #f1f1f1;
      margin: 0;
      border: 1px solid;
      border-radius: 1rem;
      align-items: stretch;
    }

    .header {
    display: flex;
    justify-content: center;
    background-color: #3778c2;
    color: #fff;
    height: 7rem;
    align-items: center;
    border-top-left-radius: 14px;
    border-top-right-radius: 14px;
    }

    h1 {
      text-align: center;
      font-family: 'Proxima Nova', 'sans-serif';
      font-weight: normal;
      color: #fff;
    }

    /* h2 {
      font-size: 24px;
      margin-bottom: 20px;
      color: #fff;
    }

  /* Text Styles */
  p {
text-align: center;
    margin: 0;
    font-size: larger;
    background-color: white;
  } */

  /* List Styles */
  ul {
    list-style: none;
    padding: 0;
    margin: 0;
  }

  li {
    display: flex;
    align-items: center;
    justify-content: space-between;
    background-color: #fff;
    padding: 10px;
    margin-right: 1rem;
    margin-left: -2rem;
    margin-bottom: 1rem;
    border-radius: 1rem;
  }

  li p {
    font-family: 'Proxima Nova', sans-serif;
    font-weight: bold;
    color: #3778c2;
    margin: 0;
  }

 /* Button Styles */
  .button {
    display: inline-block;
    padding: 10px 20px;
    background-color: #3778c2;
    color: #fff;
    text-decoration: none;
    font-family: 'Proxima Nova', sans-serif;
    font-weight: bold;
    border-radius: 4px;
  }

 /* Footer Styles */
  footer {
background-color: #5fb523;
    color: #fff;
    text-align: center;
    position: fixed;
    bottom: 0;
    left: 0;
    width: 100%;
    border-bottom-left-radius: 1rem;
    border-bottom-right-radius: 1rem;
    height: 16vh;
    display: flex;
    align-items: center;
    justify-content: center;
  }

a {
background-color: #5fb523;
    color: #fff;
    font-size: x-large;
    border: 1px solid;
    padding: 1rem;
    text-decoration: none;
}
    /* Category Styles */
    .transactions-container {
        display: flex;
        flex-direction: column;
        gap: 1rem;
      }
    .notice {
      display: none;
    }
      .transactions {
        display: flex;
        align-items: center;
        height: 5rem;
        justify-content: space-between;
        background-color: #fff;
        padding: 10px;
        margin-top: 1rem;
      }

      .back-link{
       color: white;
       background-color: #3778c2;
       border: none;
       margin-left: -7rem;
      }

      .category img {
        width: 20%;
        height: 100%;
        object-fit: contain;
      }
      .material-icons {
  font-family: 'Material Icons';
    margin-left: 1rem;
    font-style: normal;
    font-size: x-large;
}
      </style>
      <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />

      </head>
      <div class='header'>
      <h2><%= link_to root_path, class: 'back-link' do %><i class="material-icons">arrow_back</i><% end %></h2>

<h1>Transactions</h1>

</div>
<div class="transactions-container">
<p>Total Amount: <%= @total_amount %></p>

<ul>
  <% @transactions.each do |transaction| %>
    <li><%= transaction.name %><br /><br />TOTAL AMOUNT:<hr> <br /><br />$<%= transaction.amount %></li>

  <% end %>
</ul>
</div>
<footer>
<%= link_to 'Add a new transaction', new_category_transaction_path(@category) %>
</footer>

app/views/transactions/new.html.erb
<!-- app/views/transactions/new.html.erb -->
<head>
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

  <style>
    body {
      min-height: 100vh;
      display: flex;
      flex-direction: column;
      justify-content: flex-start;
      background-color: #f1f1f1;
      margin: 0;
      border: 1px solid;
      border-radius: 1rem;
      align-items: stretch;
    }

    .header {
    display: flex;
    gap: 2.5rem;
    margin-left: 1re;
    background-color: #3778c2;
    color: #fff;
    height: 8rem;
    align-items: center;
    border-top-left-radius: 14px;
    border-top-right-radius: 14px;
    }

    h1 {
    text-align: center;
    font-family: 'Proxima Nova', 'sans-serif';
    font-weight: normal;
    font-size: x-large;
    color: #fff;
    }

    h2 {
      font-size: 24px;
      margin-bottom: 20px;
      color: #fff;
    }

    .actions {
      text-align: right;
      margin-top: 10px;
    }

    .back-link {
      color: #fff;
      text-decoration: none;
      margin-right: 10px;
      font-size: 20px;
    }

    .field {
      margin-bottom: 10px;
    }

    label {
      display: block;
      font-weight: bold;
      color: #fff;
    }
    #transaction_transaction_record_id {
    width: 92%;
    padding: 10px;
    font-size: 16px;
    border-radius: 4px;
    border: 1px solid #5fb523;
    margin-left: 5px;
    margin-right: 5px;
    height: 4rem;
    margin-top: 5px;
    }
#transaction_amount {
        width: 92%;
      padding: 10px;
      font-size: 16px;
      border-radius: 4px;
      border: 1px solid #5fb523;
      margin-left: 5px;
      margin-right: 5px;
      height: 2rem;
      margin-top: 5px;
}
    input[type="text"],
    input[type="email"],
    input[type="password"],
    input[type="checkbox"] {
      width: 92%;
      padding: 10px;
      font-size: 16px;
      border-radius: 4px;
      border: 1px solid #5fb523;
      margin-left: 5px;
      margin-right: 5px;
      height: 2rem;
      margin-top: 5px;
    }

    input[type="submit"] {
    padding: 12px 24px;
    position: fixed;
    font-size: larger;
    background-color: #3778c2;
    color: #fff;
    text-decoration: none;
    border: white;
    border-radius: 4px;
    transition: background-color 0.3s;
    margin-top: -17.2rem;
    width: 100#;
    margin-left: 21rem;
    }

    input[type="submit"]:hover {
      background-color: #5fb523;
    }

     p {
      display: none;
      }

    .material-icons {
      font-family: 'Material Icons';
      margin-left: 1rem;
      font-style: normal;
      font-size: x-large;
    }
  </style>
</head>
<div class='header'>
<h2><%= link_to category_transactions_path(@category), class: 'back-link' do %><i class="material-icons">arrow_back</i><% end %></h2>

<h1>New Transaction</h1>

</div>
<%= form_with(model: [@category, @transaction], local: true) do |form| %>
  <div>
    <%= form.text_field :name, required: true, placeholder: "Enter the transaction name please" %>
  </div>

  <div>
    <%= form.number_field :amount, required: true, placeholder: "Enter the transaction amount please" %>
  </div>

  <div>
    
<%= form.collection_select :transaction_record_id, Category.all, :id, :name, { prompt: 'Select category' } %>

  </div>

  <div>
    <%= form.submit 'Save' %>
  </div>
<% end %>